export default {
  iconChat: require("./icon/bt_chat.png"),
  iconChatActive: require("./icon/bt_chat_active.png"),
  iconForum: require("./icon/bt_forum.png"),
  iconForumActive: require("./icon/bt_forum_active.png"),
  iconMe: require("./icon/bt_me.png"),
  iconMeActive: require("./icon/bt_me_active.png"),
  iconWork: require("./icon/bt_work.png"),
  iconWorkActive: require("./icon/bt_work_active.png"),
  iconResume: require("./icon/bt_resume.png"),
  iconResumeActive: require("./icon/bt_resume_active.png"),
  iconSuccess: require("./icon/icon_successful.png"),
  iconBack: require("./icon/icon_back.png"),
  iconDown: require("./icon/icon_down.png"),
  iconBuy: require("./icon/icon_buy.png"),
  iconPreview: require("./icon/icon_preview.png"),
  iconRefresh: require("./icon/icon_refresh.png"),
  iconEdu: require("./icon/icon_package.png"),
  iconEduTime: require("./icon/icon_edu.png"),
  iconBirth: require("./icon/icon_birth.png"),
  iconEdit: require("./icon/edit.png"),
  iconNoData: require("./icon/icon_nodata.png"),
  iconBangzhu: require("./icon/icon_bangzhu.png"),
  iconChongzhi: require("./icon/icon_chongzhi.png"),
  iconCollection: require("./icon/icon_collection.png"),
  iconGuangbo: require("./icon/icon_guangbo.png"),
  iconJuxing: require("./icon/icon_juxing.png"),
  iconTixian: require("./icon/icon_tixian.png"),

  btChatNormal: require("./tabbar/bt_chat_normal.png"),
  btChatActive: require("./tabbar/bt_chat.png"),
  btForumNormal: require("./tabbar/bt_forum_normal.png"),
  btForumActive: require("./tabbar/bt_forum.png"),
  btResumeNormal: require("./tabbar/bt_resume_normal.png"),
  btResumeActive: require("./tabbar/bt_resume.png"),
  btWorkNormal: require("./tabbar/bt_work_normal.png"),
  btWorkActive: require("./tabbar/bt_work.png"),

  // me.js

  iconJinggao: require("./icon/jinggao.png"),
  iconLipin: require("./icon/lipin.png"),
  iconQianight: require("./icon/qian_right.png"),
  iconShape: require("./icon/Shape.png"),
  iconOval: require("./icon/Oval.png"),
  iconShenfen: require("./icon/shenfen.png"),
  iconShezhi: require("./icon/shezhi.png"),
  iconYanzheng: require("./icon/yanzheng.png"),
  iconZhichizhongxin: require("./icon/zhichizhongxin.png"),
  iconSearch: require("./icon/icon_sousuo.png"),

  //home.js
  yanjing: require("./icon/yanjing.png"),
  money: require("./icon/money.png"),
  mairu: require("./icon/mairu.png"),
  maichu: require("./icon/maichu.png"),
  group: require("./icon/group.png")
};
